branch-defaults:
  master:
    environment: happyfeet
global:
  application_name: HappyFeet
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.2 running PHP 5.6
  default_region: us-east-1
  profile: eb-cli
  sc: git
